model_path: "OpenGVLab/InternVL3-1B"
device: "auto" 
image_input_size: 448

imagenet_mean: [0.485, 0.456, 0.406]
imagenet_std: [0.229, 0.224, 0.225]

generation_config:
  max_new_tokens: 1024
  do_sample: true
